---------------------------------------------------------------------------
-- $Id: medley-firebird-drop.sql,v 1.1 2004/04/09 16:29:53 maciek Exp $
-- 
-- Remove the database structure for Medley application.
-- 
-- author:  Maciek Makowski
-- version: $Revision: 1.1 $ 
-- date:    $Date: 2004/04/09 16:29:53 $
---------------------------------------------------------------------------

DROP TRIGGER TRG_RECORD_LOANS_INSERT;
DROP TABLE RECORD_LOANS;
DROP TRIGGER TRG_ALBUM_LOANS_INSERT;
DROP TABLE ALBUM_LOANS;
DROP TRIGGER TRG_BORROWERS_INSERT;
DROP TABLE BORROWERS;
DROP TRIGGER TRG_TRACK_AUDITIONS_INSERT;
DROP TABLE TRACK_AUDITIONS;
DROP TRIGGER TRG_RECORD_AUDITIONS_INSERT;
DROP TABLE RECORD_AUDITIONS;
DROP TRIGGER TRG_ALBUM_AUDITIONS_INSERT;
DROP TABLE ALBUM_AUDITIONS;
DROP TRIGGER TRG_ARTIST_RATINGS_INSERT;
DROP TABLE ARTIST_RATINGS;
DROP TRIGGER TRG_TRACK_RATINGS_INSERT;
DROP TABLE TRACK_RATINGS;
DROP TRIGGER TRG_RECORD_RATINGS_INSERT;
DROP TABLE RECORD_RATINGS;
DROP TRIGGER TRG_ALBUM_RATINGS_INSERT;
DROP TABLE ALBUM_RATINGS;
DROP TRIGGER TRG_RATINGS_INSERT;
DROP TABLE RATINGS;
DROP TRIGGER TRG_RATING_GROUPS_INSERT;
DROP TABLE RATING_GROUPS;
DROP TRIGGER TRG_ARTIST_TAGS_INSERT;
DROP TABLE ARTIST_TAGS;
DROP TRIGGER TRG_TRACK_TAGS_INSERT;
DROP TABLE TRACK_TAGS;
DROP TRIGGER TRG_RECORD_TAGS_INSERT;
DROP TABLE RECORD_TAGS;
DROP TRIGGER TRG_ALBUM_TAGS_INSERT;
DROP TABLE ALBUM_TAGS;
DROP TRIGGER TRG_TAG_VALUES_INSERT;
DROP TABLE TAG_VALUES;
DROP TRIGGER TRG_TAGS_INSERT;
DROP TABLE TAGS;
DROP TRIGGER TRG_TAG_GROUPS_INSERT;
DROP TABLE TAG_GROUPS;
DROP TRIGGER TRG_TRACK_ARTISTS_INSERT;
DROP TABLE TRACK_ARTISTS;
DROP TRIGGER TRG_RECORD_ARTISTS_INSERT;
DROP TABLE RECORD_ARTISTS;
DROP TRIGGER TRG_ALBUM_ARTISTS_INSERT;
DROP TABLE ALBUM_ARTISTS;
DROP TRIGGER TRG_ARTISTS_INSERT;
DROP TABLE ARTISTS;
DROP TRIGGER TRG_TRACKS_INSERT;
DROP TABLE TRACKS;
DROP TRIGGER TRG_RECORDS_INSERT;
DROP TABLE RECORDS;
DROP TRIGGER TRG_ALBUMS_INSERT;
DROP TABLE ALBUMS;

DELETE FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME = 'GEN_RECORD_LOANS';
DELETE FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME = 'GEN_ALBUM_LOANS';
DELETE FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME = 'GEN_BORROWERS';
DELETE FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME = 'GEN_TRACK_AUDITIONS';
DELETE FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME = 'GEN_RECORD_AUDITIONS';
DELETE FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME = 'GEN_ALBUM_AUDITIONS';
DELETE FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME = 'GEN_ARTIST_RATINGS';
DELETE FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME = 'GEN_TRACK_RATINGS';
DELETE FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME = 'GEN_RECORD_RATINGS';
DELETE FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME = 'GEN_ALBUM_RATINGS';
DELETE FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME = 'GEN_RATINGS';
DELETE FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME = 'GEN_RATING_GROUPS';
DELETE FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME = 'GEN_ARTIST_TAGS';
DELETE FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME = 'GEN_TRACK_TAGS';
DELETE FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME = 'GEN_RECORD_TAGS';
DELETE FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME = 'GEN_TAG_VALUES';
DELETE FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME = 'GEN_TAGS';
DELETE FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME = 'GEN_TAG_GROUPS';
DELETE FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME = 'GEN_TRACK_ARTISTS';
DELETE FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME = 'GEN_RECORD_ARTISTS';
DELETE FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME = 'GEN_ALBUM_ARTISTS';
DELETE FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME = 'GEN_ARTISTS';
DELETE FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME = 'GEN_TRACKS';
DELETE FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME = 'GEN_RECORDS';
DELETE FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME = 'GEN_ALBUMS';
